### ISSUE TITLE
CI clean up

### ISSUE THREAD

**Issue by frenzymadness** [thoth-station/micropipenv#101]
Could we please decide which parts of micropipenv's CI to remove or fix? I mean, It's kinda misleading to contributors when a PR is merged even when a big portion of tests is red or unfinished.

- Thoth: Advise (Developer Preview) - does not work because we removed its config file
- thoth-ci/* - fail on condition-check-deploy-comment-check and are not able to run tox/pytest tests.
- tide - what this is supposed to do?

I'd say that the codebase is tested on Travis but others might also implement some important checks and if they do, we should fix them.

**Comment by goern** [comment]
Thoth: Advise (Developer Preview) is a GitHub application that is generally/for all repos enabled in this org, the same for Prow/Tide. I can have a look at disabling both for this repo only. 

aicoe-ci (or thoth-ci) should be able to run tox/pytest @harshad16

**Comment by fridex** [comment]
> Thoth: Advise (Developer Preview) is a GitHub application that is generally/for all repos enabled in this org, the same for Prow/Tide. I can have a look at disabling both for this repo only.
> 

I've quickly checked the github settings. There is no configuration option to disable the github app for just one repo in the org. Do we want to maintain a list of enabled repos, are we fine for these checks to fail for this repo, or is there a "no-op" action to be configured somehow on Thoth side?
![Screenshot_2020-07-17_13-02-09](https://user-images.githubusercontent.com/880687/87779902-e2a88580-c82d-11ea-8f92-cb52c1cb86cf.png)

**Comment by frenzymadness** [comment]
I am okay having them here because I know that only jobs I have to check are Travis and Coala but the motivation for this issue is how it looks to a new contributor.

**Comment by goern** [comment]
BTW, why have we removed `.thoth.yaml` ?

**Comment by fridex** [comment]
> BTW, why have we removed `.thoth.yaml` ?

Pipfile/Pipfile.lock is not used in this repo, requirements are managed by tox:

https://github.com/thoth-station/micropipenv/blob/0e6e0fe63ba8f155110697739f489c6fd509430e/tox.ini#L7-L16

It [lacks Pipenv support](https://github.com/tox-dev/tox-pipenv/issues/58), but there is some [tox-pipenv-install](https://pypi.org/project/tox-pipenv-install/) package on PyPI (I have never used it).

BTW we could also consider [nox](https://nox.thea.codes/en/stable/) where the installation process with Pipenv might be easier.

**Comment by fridex** [comment]
... and some tests require different packages installed to check behavior based on that - see toml/pytoml for RHEL compatibility testing.

**Comment by fridex** [comment]
With https://github.com/thoth-station/micropipenv/pull/117 Thoth integration can be enabled. Hence only Thoth CI will need to be adjusted to have all the checks green.

**Comment by goern** [comment]
/close

feel free to reopen
