### ISSUE TITLE
New patch release — v0.5.1

### ISSUE THREAD

**Issue by frenzymadness** [thoth-station/micropipenv#113]
Would it be possible to release the latest enhancenments? They are only around tests so I think that a patch release is enough.

**Comment by frenzymadness** [comment]
I have to provide SRPM for RHEL very soon — it would be nice to release it today so I can package the latest version there.

**Comment by fridex** [comment]
Released v0.5.1 - the release is available on:
* GitHub https://github.com/thoth-station/micropipenv/releases/tag/v0.5.1
* PyPI https://pypi.org/project/micropipenv/0.5.1/

**Comment by fridex** [comment]
Hope all is fine, let me know if there is anything I can help with. Thanks for the work!
