### ISSUE TITLE
micropipenv should handle issues caused by relative ordering of dependencies

### ISSUE THREAD

**Issue by fridex** [thoth-station/micropipenv#12]
**Describe the bug**

As reported in https://github.com/thoth-station/s2i-thoth/issues/39 by @4n4nd

micropipenv does not handle the relative ordering of dependencies.

**To Reproduce**
1. Reach out to https://github.com/thoth-station/s2i-thoth/issues/39
2. Check build log and installed dependencies
3. See error

**Expected behavior**

micropipenv should correctly install the dependencies

**Additional context**

As the stack supplied is already fully resolved the fix might be pretty simple - instead of issuing one pip installation, we can issue pip install for each package in the stack iteratively with --no-deps flag set (and fallback respecting errors).

**Comment by fridex** [comment]
> As the stack supplied is already fully resolved the fix might be pretty simple - instead of issuing one pip installation, we can issue pip install for each package in the stack iteratively with --no-deps flag set (and fallback respecting errors).

As we might encounter similar issues when pip-tools style requirements are used, we should be capable of handling these errors in Python s2i even for requirements.txt/requirements.in.

**Comment by 4n4nd** [comment]
What if you add one more retry for the failed dependencies, but after all other builds have finished?

**Comment by fridex** [comment]
> What if you add one more retry for the failed dependencies, but after all other builds have finished?

+1, that's what I tried to express

Currently, we install all the dependencies by exec to pip - we can install them one after another and retry the failed ones.

**Comment by 4n4nd** [comment]
Ah okay. But why the —no-deps flag?

**Comment by fridex** [comment]
> Ah okay. But why the —no-deps flag?

See https://github.com/thoth-station/micropipenv/issues/10

And more importantly - the stack present in Pipfile.lock is already fully resolved with all the dependencies pinned to specific versions. If we would install packages without `--no-deps` flag iteratively, they will also include their dependencies (latest possible) and that's what we don't want - we want to install exactly those packages that are present in the Pipfile.lock.

Another solution is to use `--no-deps` and subsequently force reinstall on dependencies to have them in other versions - 2 main drawbacks:

- we can download a package multiple times (once as a dependency, once a a "force reinstall")
- we can possibly install a package that should not be present - the package could be introduced by a package that we force reinstalled

Let me know if that's clear, I can come up with some example to make it more clear.

**Comment by 4n4nd** [comment]
Oh yes that makes a lot of sense.
Thanks!
