### ISSUE TITLE
Hardcoded pip compatibility test

### ISSUE THREAD

**Issue by frenzymadness** [thoth-station/micropipenv#120]
I'm glad we are testing micropipenv with the latest versions of pip but I have mixed feelings about hardcoded pip version in the code and the warning it produces if the pip version is different.

If I understand it correctly, the last two releases were released just to say that the micropipenv is compatible with two new releases of pip.

With my package maintainer hat on, I am not sure this approach is sustainable. Right now, I am in the situation when it does not make sense to spend my time updating micropipenv in Fedora because F33 already has version 0.5.1 and since then only non-user-facing changes were made. But if we update pip in Fedora, micropipenv will start showing the warning. The situation might be even worse for RHEL.

What if we show the warning only when something wrong happens? Something like:
```python
if __name__ == "__main__":
    logging.basicConfig(format="%(asctime)s %(name)-12s %(levelname)-6s %(message)s", datefmt="%m-%d-%y %H:%M:%S")
    try:
        return_code = main()
    except Exception:
        _check_pip_version(raise_on_incompatible=False)
        raise
    else:
        sys.exit(return_code)
```

Something like this solves only one half of the problem but it might provide enough information for a user using micropipenv in an environment where they have control of the pip and do not disturb users when nothing wrong happens.

What do you think about it?

**Comment by fridex** [comment]
+1, completely makes sense :+1:

**Comment by fridex** [comment]
Not to keep this stalled, I created #121 and mentioned you as the author, but feel free to open PR in your name.

**Comment by frenzymadness** [comment]
There are two possible problems with compatibility with pip:

* pip is too old: I think we don't have to find a solution for this because we clearly defined in `setup.py` that micropipenv needs `pip>=9`. If you install micropipenv via pip, it will automatically update pip. If you already have micropipenv and downgrade pip, you see a red warning that micropipenv needs something newer. In RPM world, we use the same `python setup.py build/install` so the package won't build if the requirement specified in `setup.py` won't be satisfied. This requirement is also reflected in the resulting RPM so it should not be installable with an older pip. The same functionality will be (hopefully) in RHEL 9 and in RHEL 8 we never change the version of the main pip.
* pip is too new: according to the [documentation](https://pip.pypa.io/en/latest/development/release-process/) pip might change any internal (non-documented) part without any warning but this might IMHO happen only every three months when a new version is released and not during a bugfix release which might happen in the meantime. Again, this is not an issue in a virtualenv where pip can automatically downgrade itself if we specify that the micropipenv requires for example `"pip>=9,<=20.1". In RPM world (Fedora) it's simple, we can just postpone an update of micropipenv until a compatible version of pip will be ready. It's even simpler in RHEL where we rebase RPMs very carefully and micropipenv won't have the full support there.

So, my proposal is to remove the check of the pip version from the codebase and use requirement specifier in `setup.py` to allow installation only with a range of supported versions. Right now it would be `install_requires=["pip>=9,<=20.2"]`. When 20.3 comes out, we can add 20.2 to our testing metrics (if there will be a reason for example 20.2 will be included in some stable distro), 20.3 will be covered by piplatest and if CI passes we can release a new version with `install_requires=["pip>=9,<=20.3"]`. That's something we will need to do every three months in January, April, July, and October. Of course, if you want to, you can do it more frequently for every bugfix release of pip but I don't think it's necessary.

The result will be that we will do a release every three months, we won't care that much about bugfix releases of pip and every version of micropipenv will be installable only with the supported versions of pip. If pip gets updated in distribution, a maintainer will be notified about it because the older version of micropipenv won't build/install with the latest pip and a new version of micropipenv should be already ready here. In this way, we shift the responsibility to package maintainer because a user has no official way to upgrade/downgrade pip if they discover that micropipenv doesn't work with the version they have.

Another aspect we will have to deal with is that pip will drop support for Python 2 in January 2021 (version 21). We can drop it as well or we can keep maintaining some LTS version with `install_requires=["pip>=9,<=20"]`. It should be also possible to keep Python 2 support with something like `install_requires=["pip>=9,<=20; python_version <= '2.7'", "pip>=9,<=21; python_version > '2.7'"]`.

Sorry for the long reading. What do you think about it?

**Comment by fridex** [comment]
> There are two possible problems with compatibility with pip:
> 
> * pip is too old: I think we don't have to find a solution for this because we clearly defined in `setup.py` that micropipenv needs `pip>=9`. If you install micropipenv via pip, it will automatically update pip. If you already have micropipenv and downgrade pip, you see a red warning that micropipenv needs something newer. In RPM world, we use the same `python setup.py build/install` so the package won't build if the requirement specified in `setup.py` won't be satisfied. This requirement is also reflected in the resulting RPM so it should not be installable with an older pip. The same functionality will be (hopefully) in RHEL 9 and in RHEL 8 we never change the version of the main pip.

Agree. Then I don't see why the referenced PR was closed with this comment https://github.com/thoth-station/micropipenv/pull/121#issuecomment-680783771

> * pip is too new: according to the [documentation](https://pip.pypa.io/en/latest/development/release-process/) pip might change any internal (non-documented) part without any warning but this might IMHO happen only every three months when a new version is released and not during a bugfix release which might happen in the meantime. Again, this is not an issue in a virtualenv where pip can automatically downgrade itself if we specify that the micropipenv requires for example `"pip>=9,<=20.1". In RPM world (Fedora) it's simple, we can just postpone an update of micropipenv until a compatible version of pip will be ready. It's even simpler in RHEL where we rebase RPMs very carefully and micropipenv won't have the full support there.

An example case where I see an issue is s2i with the following example (please correct me if my assumption is wrong here):

Python s2i is shipped with micropipenv from an RPM:

```
dnf install -y micropipenv
```

and s2i tooling manages virtual environment (or use `python3-virtualenv`, ...):

```
python3 -m venv venv
source venv/bin/activate
```

Now, after some time (e.g. 1 year later) a new pip is released. The s2i container image is still shipped with the virtual environment with an older pip release used during the s2i container build. However, a user of Python s2i sets explicitly:

```UPGRADE_PIP_TO_LATEST=1```

In that case, pip in the s2i gets updated and the micropipenv shipped with s2i might be out of date. Hence a warning message as we produce for untested pip release could be helpful.

> So, my proposal is to remove the check of the pip version from the codebase and use requirement specifier in `setup.py` to allow installation only with a range of supported versions. Right now it would be `install_requires=["pip>=9,<=20.2"]`.... snip

I see your point - this is an underpinning/overpinning issue.  The thing I don't like here is the referenced s2i case.

Also, I like the current approach because I can still use older micropipenv with pip released recently if pip did not break any internal API. If pip has different API, we try to use it but we produce a warning message if micropipenv encounters any error during the installation. Simply said - micropipenv does whatever it knows best to install software, if it fails, it notifies a user about that fact the micropipenv/pip version combination is untested.

> Another aspect we will have to deal with is that pip will drop support for Python 2 in January 2021 (version 21). We can drop it as well or we can keep maintaining some LTS version with `install_requires=["pip>=9,<=20"]`. It should be also possible to keep Python 2 support with something like `install_requires=["pip>=9,<=20; python_version <= '2.7'", "pip>=9,<=21; python_version > '2.7'"]`.

I think python 2 support is not relevant in this case as micropipenv supports only python3.

**Comment by frenzymadness** [comment]
> Agree. Then I don't see why the referenced PR was closed with this comment [#121 (comment)](https://github.com/thoth-station/micropipenv/pull/121#issuecomment-680783771)

I am sorry if it was unexpected. We might get back to it. I've just realized during testing the PR that the problem is more complex.

> Python s2i is shipped with micropipenv from an RPM:

It's not now because RPMs are still available only in Fedora. But it will be, yes.

> and s2i tooling manages virtual environment (or use `python3-virtualenv`, ...):
> 
> ```
> python3 -m venv venv
> source venv/bin/activate
> ```

We prefer `venv` whenever possible, that's correct.

> Now, after some time (e.g. 1 year later) a new pip is released. The s2i container image is still shipped with the virtual environment with an older pip release used during the s2i container build. However, a user of Python s2i sets explicitly:
> 
> `UPGRADE_PIP_TO_LATEST=1`
> 
> In that case, pip in the s2i gets updated and the micropipenv shipped with s2i might be out of date. Hence a warning message as we produce for untested pip release could be helpful.

That's not quite true. Currently, we use two separate virtual environments — for application and for tools like pipenv or micropipenv. The reason for this is that pipenv (which was added way sooner than micropipenv) has a lot of dependencies and there is a possibility that an application's dependencies may conflict with pipenv's dependencies. `UPGRADE_PIP_TO_LATEST` has an effect only in the application virtual environment so pipenv/micropipenv can depend on a different version of pip or other packages than applications.  See: https://github.com/sclorg/s2i-python-container/blob/master/3.8/s2i/bin/assemble#L22

In the future, when micropipenv will be installed everywhere from an RPM package, the situation will be similar because micropipenv will depend on the main system pip installed also from RPM package. This dependency should remain stable because the main pip will remain stable and possible issues should be uncovered during an RPM builds and tests. And again, users will be able to use whatever pip they want in the application virtual environment.

> Also, I like the current approach because I can still use older micropipenv with pip released recently if pip did not break any internal API. If pip has different API, we try to use it but we produce a warning message if micropipenv encounters any error during the installation. Simply said - micropipenv does whatever it knows best to install software, if it fails, it notifies a user about that fact the micropipenv/pip version combination is untested.

I think that we have two options here:
* **pin pip version** — you'll be able to install micropipenv only with supported pips, the installation process automatically upgrade/downgrade your pip for you and if there is anything else in a virtualenv incompatible with what micropipenv needs you'll be notified by pip
* **keep the warning** — you'll be able to install micropipenv with whatever pip (new enough) you have. If your pip is too new and possibly incompatible micropipenv notifies you and it's up to you to handle the problem (downgrade pip).

After all this brainstorming, I'm fine with both options. I was afraid that the work with keeping pip version in the codebase and releasing a new version with every change of it will be hard to maintain but it now seems inevitable.

> I think python 2 support is not relevant in this case as micropipenv supports only python3.

My bad, I don't know what I was thinking about.

Side note. Pip's docs about releases say:
> Because releases are made direct from the master branch, it is essential that master is always in a releasable state. It is acceptable to merge PRs that partially implement a new feature, but only if the partially implemented version is usable in that state (for example, with reduced functionality or disabled by default). In the case where a merged PR is found to need extra work before being released, the release manager always has the option to back out the partial change prior to a release. The PR can then be reworked and resubmitted for the next release.

So it might be a good idea to include pip's master to our CI to discover an issue before the next pip release.

**Comment by fridex** [comment]
> I think that we have two options here:
> 
> * **pin pip version** — you'll be able to install micropipenv only with supported pips, the installation process automatically upgrade/downgrade your pip for you and if there is anything else in a virtualenv incompatible with what micropipenv needs you'll be notified by pip
> * **keep the warning** — you'll be able to install micropipenv with whatever pip (new enough) you have. If your pip is too new and possibly incompatible micropipenv notifies you and it's up to you to handle the problem (downgrade pip).
> 
> After all this brainstorming, I'm fine with both options. I was afraid that the work with keeping pip version in the codebase and releasing a new version with every change of it will be hard to maintain but it now seems inevitable.

From the PyPI package point of view I would like to stick with the latter solution - keep the warning but only if something goes wrong. We don't need to release micropipenv on each pip release and if pip changes its internal API users get notified about the fact the buggy micropipenv release was not tested with pip used.

I don't know the impact on the RPM side if there is used `python setup.py build/install`. Will this solution introduce any burden on rpm package maintenance side? Or could RPM restrict the upper bounder of the version range specification? I don't want to introduce more work on the RPM side.

> Side note. Pip's docs about releases say:
> 
> > Because releases are made direct from the master branch, it is essential that master is always in a releasable state. It is acceptable to merge PRs that partially implement a new feature, but only if the partially implemented version is usable in that state (for example, with reduced functionality or disabled by default). In the case where a merged PR is found to need extra work before being released, the release manager always has the option to back out the partial change prior to a release. The PR can then be reworked and resubmitted for the next release.
> 
> So it might be a good idea to include pip's master to our CI to discover an issue before the next pip release.

Nice catch, I opened https://github.com/thoth-station/micropipenv/pull/122 to support this :+1:

**Comment by frenzymadness** [comment]
Thank you for your patience with my ongoing brainstorming.

> From the PyPI package point of view I would like to stick with the latter solution - keep the warning but only if something goes wrong. We don't need to release micropipenv on each pip release and if pip changes its internal API users get notified about the fact the buggy micropipenv release was not tested with pip used.

You are right. Could you please reopen the PR with the warning and modify it to catch an incompatibility in imports? We can also test it with some older pip.

> I don't know the impact on the RPM side if there is used `python setup.py build/install`. Will this solution introduce any burden on rpm package maintenance side? Or could RPM restrict the upper bounder of the version range specification? I don't want to introduce more work on the RPM side.

I am able to add the version restrictions there manually if it will be needed.

**Comment by fridex** [comment]
> Thank you for your patience with my ongoing brainstorming.

No problem at all. Actually I like our conversations as they lead to better software and better solutions. The cross-team coop is very healthy :+1: Thank you!

> > From the PyPI package point of view I would like to stick with the latter solution - keep the warning but only if something goes wrong. We don't need to release micropipenv on each pip release and if pip changes its internal API users get notified about the fact the buggy micropipenv release was not tested with pip used.
> 
> You are right. Could you please reopen the PR with the warning and modify it to catch an incompatibility in imports? We can also test it with some older pip.

Reopened in https://github.com/thoth-station/micropipenv/pull/121. Would it be OK for you to proceed with #121 and add check for the older versions in a separate PR, possibly with adding a new test to tox?

> > I don't know the impact on the RPM side if there is used `python setup.py build/install`. Will this solution introduce any burden on rpm package maintenance side? Or could RPM restrict the upper bounder of the version range specification? I don't want to introduce more work on the RPM side.
> 
> I am able to add the version restrictions there manually if it will be needed.

Sounds reasonable :+1:

**Comment by fridex** [comment]
I'll reopen this one until we consolidate on #124 and #123

**Comment by fridex** [comment]
The referenced issues fixed this. I'll close this. Feel free to reopen if anything more to discuss.
