### ISSUE TITLE
Are we ready for 1.0.0 release?

### ISSUE THREAD

**Issue by fridex** [thoth-station/micropipenv#130]
**Is your feature request related to a problem? Please describe.**

It looks like the codebase got stabilized, micropipenv was triggered a few hundred times during container builds. From a feature point of view, it looks like the tool does its job and, as of now, we don't plan to add any additional functionality.

Are we ready for a 1.0.0 release? Do we want it? Or should we stick with [0ver](https://0ver.org/)?

**Comment by fridex** [comment]
CC @frenzymadness

**Comment by fridex** [comment]
One missing feature in issues is https://github.com/thoth-station/micropipenv/issues/33. I don't think it is critical and it does not have any impact on the micropipenv functionality. I would not consider it as a blocker for a possible 1.0.0 release.

**Comment by frenzymadness** [comment]
It's just my personal preference, but I like semantic versioning.

From its doc:
```
Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

```

From this point of view, we are ready to release version 1.0.0 and obey the rules of semantic versioning for future releases.

**Comment by fridex** [comment]
> From this point of view, we are ready to release version 1.0.0 and obey the rules of semantic versioning for future releases.

OK, sounds good. +1 also on my side for a 1.0.0 release.

I'll keep this open one day for the community, I'll create the release tomorrow if no objections will be received.
