### ISSUE TITLE
Do we need `aicor-ci.yaml` in this repo?

### ISSUE THREAD

**Issue by bissenbay** [thoth-station/micropipenv#143]
Related-To: https://github.com/thoth-station/thoth-application/issues/545#issuecomment-735914655

**Comment by fridex** [comment]
See https://github.com/AICoE/aicoe-ci/issues/40

**Comment by frenzymadness** [comment]
I am sorry but I am not familiar with AICoE standards, could you please elaborate more.

**Comment by fridex** [comment]
> I am sorry but I am not familiar with AICoE standards, could you please elaborate more.

@harshad16 works on a CI that is in AICoE org. The CI is configured using `aicoe-ci.yaml` and we recently did changes in our project that required changes in the configuration file hence the issue. This repo is somehow an exception in the whole thoth-station organization as we do not use AICoE CI in it (as of now).

**Comment by harshad16** [comment]
thanks, @fridex  for simplifying this.
will get the proper structure in, so that user/collaborators don't get confused based on the ci check statues, as we don't need build check and pytest checks from the aicoe-ci, will get them removed.

**Comment by fridex** [comment]
@harshad16, thanks!
