### ISSUE TITLE
Wrong package name in lock file results package not being installed - doesn't match pipenv behavior

### ISSUE THREAD

**Issue by tumido** [thoth-station/micropipenv#148]
**Describe the bug**
When package name in `[packages]` list doesn't match the name in its `setup.py`, micropipenv fails to install. This is inconsistent with `pipenv`.

**To Reproduce**

Prerequisites below. Try to install https://github.com/jundongl/scikit-feature as `scikit-feature` while it's [`setup.py`](https://github.com/jundongl/scikit-feature/blob/48cffad4e88ff4b9d2f1c7baffb314d1b3303792/setup.py#L3) states the name to be `skfeatures`.

```
$ cat Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
scikit-feature = {git = "https://github.com/jundongl/scikit-feature.git", ref="48cffad4e88ff4b9d2f1c7baffb314d1b3303792"}

[dev-packages]

[requires]
python_version = "3.8"

$ cat Pipfile.lock
{
    "_meta": {
        "hash": {
            "sha256": "7c193a43cd064e999632361e52546519a15ad945a68ff6758f3825966be825b3"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "scikit-feature": {
            "git": "https://github.com/jundongl/scikit-feature.git",
            "ref": "48cffad4e88ff4b9d2f1c7baffb314d1b3303792"
        }
    },
    "develop": {}
}
```
### Pipenv behavior

```
$ pipenv install
Installing dependencies from Pipfile.lock (e825b3)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:49
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

$ pipenv run python -c "import skfeature; print('success')"
success
```
### Micropipenv behavior

```
$ micropipenv install
---------------------------------- Pipfile.lock ----------------------------------
{
    "_meta": {
        "hash": {
            "sha256": "7c193a43cd064e999632361e52546519a15ad945a68ff6758f3825966be825b3"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "scikit-feature": {
            "git": "https://github.com/jundongl/scikit-feature.git",
            "ref": "48cffad4e88ff4b9d2f1c7baffb314d1b3303792"
        }
    },
    "develop": {}
}
---------------------------------- Pipfile.lock ----------------------------------
!!! Requirement scikit-feature uses a VCS version: {'git': 'https://github.com/jundongl/scikit-feature.git', 'ref': '48cffad4e88ff4b9d2f1c7baffb314d1b3303792'}
Collecting scikit-feature
  Cloning https://github.com/jundongl/scikit-feature.git (to revision 48cffad4e88ff4b9d2f1c7baffb314d1b3303792) to /tmp/pip-install-kmmnezoz/scikit-feature_00cf727f42244e9897ce2dfcc6f254c5
  WARNING: Generating metadata for package scikit-feature produced metadata for project name skfeature. Fix your #egg=scikit-feature fragments.
ERROR: Requested skfeature from git+https://github.com/jundongl/scikit-feature.git@48cffad4e88ff4b9d2f1c7baffb314d1b3303792#egg=scikit-feature (from -r /tmp/requirements_micropipenv-ofk7pdts.txt (line 2)) has different name in metadata: 'skfeature'
Failed to install requirements, dependency 'scikit-feature' could not be installed

$ pipenv run python -c "import skfeature;print('success')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'skfeature'
```

**Expected behavior**
The behavior should be consistent

**Additional context**
This behavior changed in `micropipenv` fairly recently as it seems from  https://github.com/aicoe-aiops/ocp4-anomaly-detection-internal/pull/71

**Comment by fridex** [comment]
Based on the error log produced:

```
Collecting scikit-feature
  Cloning https://github.com/jundongl/scikit-feature.git (to revision 48cffad4e88ff4b9d2f1c7baffb314d1b3303792) to /tmp/pip-install-kmmnezoz/scikit-feature_00cf727f42244e9897ce2dfcc6f254c5
  WARNING: Generating metadata for package scikit-feature produced metadata for project name skfeature. Fix your #egg=scikit-feature fragments.
ERROR: Requested skfeature from git+https://github.com/jundongl/scikit-feature.git@48cffad4e88ff4b9d2f1c7baffb314d1b3303792#egg=scikit-feature (from -r /tmp/requirements_micropipenv-ofk7pdts.txt (line 2)) has different name in metadata: 'skfeature'
```

I would consider this as a bug in Pipenv rather than in micropipenv. pip added few metadata checks in recent releases which could cause these failures. If Pipenv updates its bundled pip, this behavior could be probably seen also in Pipenv. What is your pip version?

**Comment by tumido** [comment]
```
$ pipenv --version
pipenv, version 2020.11.15
```

I don't know if this is a bug in either of those tools :wink: I'm just raising awareness of this inconsistency. I also understand that user is not supposed to name the packages in Pipfile differently to what they are named in the `setup.py`. :smile:

**Comment by fridex** [comment]
> ```
> $ pipenv --version
> pipenv, version 2020.11.15
> ```

And pip version used with micropipenv? (micropipenv uses pip under the hood, but does not bundle it as Pipenv)


> I don't know if this is a bug in either of those tools  I'm just raising awareness of this inconsistency. I also understand that user is not supposed to name the packages in Pipfile differently to what they are named in the `setup.py`.

+1, thanks for that! :+1:

**Comment by tumido** [comment]
```
$ pip --version
pip 20.3.1 from /home/tcoufal/.local/share/virtualenvs/x-fJamIjPy/lib/python3.8/site-packages/pip (python 3.8)

$ micropipenv --version
1.0.1
```

**Comment by fridex** [comment]
> ```
> $ pip --version
> pip 20.3.1 from /home/tcoufal/.local/share/virtualenvs/x-fJamIjPy/lib/python3.8/site-packages/pip (python 3.8)

It looks like this is a behavior change with the new pip resolver:

https://github.com/pypa/pip/blob/cdc5422ed5ec2fb00ce6fd7631f76afbcd6a685b/tests/functional/test_install.py#L1459-L1478

You can use an older pip release to suppress this (<20.3) or use the legacy resolver to bypass the check and mimic Pipenv behavior:

```
micropipenv install -- --use-deprecated=legacy-resolver
```

... but ideally fix the name in requirements.

Thanks for letting us know this :+1:

**Comment by fridex** [comment]
I'm about to close this issue. The error message produced should point users to the fix for this. This behavior is not micropipenv logic, but pip's logic so I think it's safe to keep this as is.

Thanks for the report and feel free to reopen if you have any other concerns or suggestions.
