### ISSUE TITLE
Support for PEP-517/PEP-518

### ISSUE THREAD

**Issue by fridex** [thoth-station/micropipenv#149]
**Is your feature request related to a problem? Please describe.**

Let's have a look if we want to incorporate PEP-517 and PEP-518 into micropipenv. First, let's discuss if we want to have this extension in s2i and in micropipenv itself. More precisely, the tool could support `pyproject.toml` for dependency specification and install dependencies based on the specification stated. 

**Additional context**
https://www.python.org/dev/peps/pep-0517/
https://www.python.org/dev/peps/pep-0518/

**Comment by fridex** [comment]
CC @frenzymadness

**Comment by frenzymadness** [comment]
Could you please elaborate more? What is the benefit of parsing pyproject.toml when we ideally want to install sdist/wheel and not build them?

**Comment by fridex** [comment]
This is relevant to https://github.com/release-engineering/cachito/issues/342, in which case PEP-517/PEP-518 support was raised. I wonder whether micropipenv could be helpful on this front.

**Comment by frenzymadness** [comment]
I'm sorry but I don't understand the relation between Pipfile mentioned in the cachito issue and pyproject.toml and PEP-51[78].

**Comment by fridex** [comment]
> I'm sorry but I don't understand the relation between Pipfile mentioned in the cachito issue and pyproject.toml and PEP-51[78].

The conversation where peps were mentioned was not on GitHub, sadly.

To the pep support - maybe I'm trying to fit too much into micropipenv here, just wanted to have open discussion about it. The point was to add support for `pyproject.toml` so micropipenv could install dependencies needed based on `pyproject.toml` (besides Pipenv files, Poetry lock files or requirements.txt files, could be under different sub-command). I haven't checked PEPs in detail, just wanted to know position here for possible `pyproject.toml` support and if that would be something that could fit into micropipenv.

**Comment by frenzymadness** [comment]
As I understand it, we can fully rely on pip here. Basically, PEP 517/518 are both about building wheels from source tarballs (sdist). PEP 518 defines how you can specify build dependencies for your project and PEP 517 specifies what to call to build a wheel from sdist (build backend). Both are already implemented in pip.

Micropipenv is designed to install packages from a list of dependencies. If a package in this list is not available as a wheel, pip can handle it and build a wheel from if either using setup.py of pyproject.toml. It's possible to implement PEP 518 here to make micropipenv able to install build dependencies but without PEP 517 is does not make sense to me. And implementing PEP 517 would mean completely copy what's already implemented in pip.

I don't think it makes sense to make micropipenv another build frontend for PEP 51[78].

What might make sense (🤔) is to make micropipenv a proxy to pip so something like `micropipenv install .` would not fail but instead uses pip to install the local project from with setup.py/pyproject.toml. But I'm not sure that it's useful and worth it.

I'm sorry if I still misunderstand you. If so, could you please describe a use case we can discuss further?

**Comment by fridex** [comment]
Thanks for the extensive reply. I think it makes sense to keep it as is, as you wrote. Let's close this. 👍
