### ISSUE TITLE
toml modules in tests

### ISSUE THREAD

**Issue by frenzymadness** [thoth-station/micropipenv#157]
https://github.com/thoth-station/micropipenv/blob/537df19fae5ba486def3098be631fbe75d66b148/tests/test_micropipenv.py#L94-L101

Hello. I'm probably just blind but how the test mentioned above can work when it runs micropipenv in a virtual environment and reads Pipfile without toml or pytoml modules installed in the virtual environment.

I've realized that many tests of pipenv and poetry functionalities need toml but only a limited subset has it installed manually in the venv.

**Comment by fridex** [comment]
> Hello. I'm probably just blind but how the test mentioned above can work when it runs micropipenv in a virtual environment and reads Pipfile without toml or pytoml modules installed in the virtual environment.

This test does not require toml/pytoml. The test installs from Pipifle.lock and micropipenv does not read Pipfile, unless [`--deploy` flag is used](https://github.com/thoth-station/micropipenv#micropipenv-install---deploy).

**Comment by frenzymadness** [comment]
That makes perfect sense! So right now, we have only two tests requiring one of the toml modules?

**Comment by fridex** [comment]
> That makes perfect sense! So right now, we have only two tests requiring one of the toml modules?

Yes, sounds like poetry installation method and pipenv with pipfile parsing. Is there anything to be improved?

**Comment by frenzymadness** [comment]
I see it only in `test_install_poetry` and `test_install_poetry_vcs`.

**Comment by fridex** [comment]
Maybe also `test_install_pipenv_deploy_error_hash` (?) and `test_import_toml` could be also considered. We can definitely add more if required. Is this related to any issue?

**Comment by frenzymadness** [comment]
I don't see where a toml module is installed in `test_install_pipenv_deploy_error_hash`.

https://github.com/thoth-station/micropipenv/blob/537df19fae5ba486def3098be631fbe75d66b148/tests/test_micropipenv.py#L365-L375

**Comment by fridex** [comment]
These tests are using pytoml installed into environment where tests are executed (the process where pytest is running). To handle pytoml installation, these tests need to be rewritten to spawn a sub-process which would use python from venv (that would have pytoml package installed outside of the one in the pytest environment).

Nevetheless I suspect pytoml is brought to environment as an indirect dependency of one of test dependencies. To have this properly maintained, it should be added to the dependency listing.

**Comment by fridex** [comment]
> Nevetheless I suspect pytoml is brought to environment as an indirect dependency of one of test dependencies. To have this properly maintained, it should be added to the dependency listing.

Yes, I've just checked that toml is a dependency of pytest itself.

**Comment by fridex** [comment]
> These tests are using pytoml installed into environment where tests are executed (the process where pytest is running). To handle pytoml installation, these tests need to be rewritten to spawn a sub-process which would use python from venv (that would have pytoml package installed outside of the one in the pytest environment).

I think that's why you originally run a sub-process to verify pytest/toml installation checks:

https://github.com/thoth-station/micropipenv/blob/537df19fae5ba486def3098be631fbe75d66b148/tests/test_micropipenv.py#L825-L838

**Comment by fridex** [comment]
@frenzymadness can we call this resolved or is there any action to be taken?

**Comment by frenzymadness** [comment]
For the context: I've realized that when I've tried to find a way how to run tests of micropipenv with a toml module installed from RPM to check their compatibility. I was thinking that there might be a way how to let micropipenv use the module from system site-packages but as you pointed out, toml will be always there because it's a direct dependency of pytest and its modules.

It might be possible to do it but it's not worth the trouble.

**Comment by fridex** [comment]
> toml will be always there because it's a direct dependency of pytest and its modules.

Maybe we should include pytoml in the direct dependency listing of testsuite (as it is a direct dependency). If pytest drops toml from its requirements someday in the future, tests will break.

**Comment by frenzymadness** [comment]
It would be great to run micropipenv in isolated environments. In that case, it should be easy to allow access to system site-packages and test it also with the system toml modules.

**Comment by fridex** [comment]
> It would be great to run micropipenv in isolated environments. In that case, it should be easy to allow access to system site-packages and test it also with the system toml modules.

Is this something that should be done in s2i/rpm tests? Not sure if it fits into python-only micropipev testsuite.

**Comment by frenzymadness** [comment]
I can imagine this scenario although I'm not sure it's worth it:
1. Every single tests invoking micropipenv as a module or script would run in a virtual environment separated from pytest and all other test dependencies.
2. Test where a toml module is needed would by default install the chosen implementation to the venv in advance. No more ambiguity caused by test dependencies.
3. In a special case, not necessarily tested in the CI here, the venv would have an access to the system site-packages which would allow us to test micropipenv with the version of pytoml or toml we have in OS.

So from the current switch between toml/pytoml it would be toml/pytoml/system when the system is then the responsibility of the maintainer to make sure a toml module is available.

BTW, we are able to install rpm packages into the container in the ci so it should be possible here to test it with the toml from fedora and downstream with the pytoml from enterprise linux.
