### ISSUE TITLE
Support injecting environment variables into Pipenv files

### ISSUE THREAD

**Issue by fridex** [thoth-station/micropipenv#158]
**Is your feature request related to a problem? Please describe.**

To be compatible with Pipenv, we should add capability to inject environment variables into Pipenv files. See [Pipenv docs for more info](https://pipenv.pypa.io/en/latest/advanced/#injecting-credentials-into-pipfiles-via-environment-variables).

**Describe the solution you'd like**

micropipenv can inject environment variables to entries in `source` section.

**Comment by frenzymadness** [comment]
If there is no rush in implementing this, we'll have a few high school interns in our team in May and this looks like a good project one of them might be interested in. What do you think?

**Comment by fridex** [comment]
> If there is no rush in implementing this, we'll have a few high school interns in our team in May and this looks like a good project one of them might be interested in. What do you think?

+1 on my side. :+1: We do not have a direct use case for this as of now.

**Comment by Misoslav** [comment]
#177
Should it also find enviromental variables in .env files?

**Comment by fridex** [comment]
> #177
> Should it also find enviromental variables in .env files?

Good point 👍🏻  - it would be helpful. That way the environment variable injecting feature would be fully compatible with [Pipenv's .env handling](https://docs.pipenv.org/advanced/#automatic-loading-of-env).

**Comment by fridex** [comment]
Actually, reading the docs - might be not needed as micropipenv does not manage a virtual environment.
