### ISSUE TITLE
PEP-665 support

### ISSUE THREAD

**Issue by fridex** [thoth-station/micropipenv#184]
**Is your feature request related to a problem? Please describe.**

See https://discuss.python.org/t/pep-665-specifying-installation-requirements-for-python-projects/9911

**Comment by frenzymadness** [comment]
I have to admit, this is kinda complex. If accepted, it might make sense to switch the locking mechanism of micropipenv from pipenv-style to this.

**Comment by frenzymadness** [comment]
The PEP is still a draft so I don't think the priority is correct here.
