### ISSUE TITLE
Python2 support

### ISSUE THREAD

**Issue by fridex** [thoth-station/micropipenv#19]
**Is your feature request related to a problem? Please describe.**

In order to use this tool in Python s2i, it would be nice to also support EOL Python2.

TODO

- [ ] make micropipenv compatible with Python2
- [ ] create testsuite for running micropipenv in Python2/Python3 possibly in different versions (tox?)

**Related discussion**

https://github.com/sclorg/s2i-python-container/pull/367

**Comment by fridex** [comment]
CC @frenzymadness

**Comment by frenzymadness** [comment]
Tox is a great idea here. We can then use it to test micropipenv with all supported Pythons.

**Comment by fridex** [comment]
Closing this, see #18 for more info.
