### ISSUE TITLE
Package as RPM

### ISSUE THREAD

**Issue by fridex** [thoth-station/micropipenv#20]
**Is your feature request related to a problem? Please describe.**

Let's have micropipenv as an RPM.

[1] https://fedoraproject.org/wiki/Packit

**Related discussion**
https://github.com/sclorg/s2i-python-container/pull/367

**Comment by fridex** [comment]
CC @frenzymadness

**Comment by frenzymadness** [comment]
Don't forget to start with some helper like `pyp2rpm`. I'll take a look at this if nobody will be faster than me.

**Comment by frenzymadness** [comment]
Here are RPMs for multiple Fedora releases in COPR: https://copr.fedorainfracloud.org/coprs/lbalhar/micropipenv/build/1304404/

Could please somebody test them? I did a quick test with one simple Pipfile and it seems to be okay. If you can test it and let me know, I'll prepare it as a proper Fedora package then.

**Comment by fridex** [comment]
Thanks! I've run the installation part of micropipenv testsuite inside f30, f31, f32 containers. It looks like it works:


```
dnf install -y git 'dnf-command(copr)'
dnf copr enable lbalhar/micropipenv
dnf install python3-micropipenv
git clone https://github.com/thoth-station/micropipenv
cd micropipenv
rm Pipfile Pipfile.lock   # to make sure the test files are used
cd tests/data/install
```

```
#!/bin/bash -ex

for d in `ls -A1`; do
        [ "$d" == "test.sh" -o "$d" == "venv" ] && continue
        rm -rf venv
        python3 -m venv venv
        . venv/bin/activate
        pushd $d
        micropipenv --verbose --verbose install --dev
        popd
done
```

**Comment by fridex** [comment]
rawhide works fine for me as well :+1:

**Comment by frenzymadness** [comment]
Copr contains builds with the latest version. I'm going to prepare a package review bug.

**Comment by frenzymadness** [comment]
Package review bug: https://bugzilla.redhat.com/show_bug.cgi?id=1813263

**Comment by frenzymadness** [comment]
Package is approved. It will be soon in rawhide. For all other active branches, there are fresh updates:
* F32: https://bodhi.fedoraproject.org/updates/FEDORA-2020-ddf4c8c827
* F31: https://bodhi.fedoraproject.org/updates/FEDORA-2020-a4d894708a
* F30: https://bodhi.fedoraproject.org/updates/FEDORA-2020-5eb0c28ee6

It would be nice if somebody can find some time, test the builds and give them some karma.

**Comment by frenzymadness** [comment]
Micropipenv (0.1.4) is available in Fedora rawhide, 32, 31 and 30.
