### ISSUE TITLE
New release with pip 22 support

### ISSUE THREAD

**Issue by frenzymadness** [thoth-station/micropipenv#223]
SSIA, we need to update micropipenv in Fedora before we update pip to 22.

**Comment by fridex** [comment]
I'm wondering what would be the most appropriate release given the changes - patch or new minor release?

**Comment by frenzymadness** [comment]
I think both are fine. Depends on whether we fix incompatibility with pip 22 (patch) or add the compatibility as a new feature (minor).

**Comment by fridex** [comment]
The release is available https://pypi.org/project/micropipenv/1.2.1/
