### ISSUE TITLE
Disable Thot bot (sesheta) on this project

### ISSUE THREAD

**Issue by frenzymadness** [thoth-station/micropipenv#242]
I'd like to disable Thot bot (sesheta) on this project. In my opinion, it generates unnecessary comments and does not add any value to my workflows.

@goern what do you think?

**Comment by goern** [comment]
I'm good with hat, if you could give a little insight what you like/dont like, what you would like to see, etc.

@Gkrumbach07 @mayaCostantini 
/kind feature
/priority critical-urgent
/triage accepted

**Comment by frenzymadness** [comment]
I'm just used to managing my repositories manually. For example, I don't like the auto-closing of issues. Also, every new PR receives an immediate comment from the bot that the issue is not approved, which is obvious for new PRs. Github has its own standard way for approving of PRs and I like it more than the special commands. One last thing is that the comment from the bot in the latest PR says that I should request a review from myself.

**Comment by goern** [comment]
Hey @frenzymadness I think you are talking about all the Prow activity you see on issues. 

wrt to approving PR, the Prow plugin and GitHub are equivalent, you can use one or the other with the same results. so if you like to click approve on the github web UI, feel free, it will also add the 'approved' label. I wonder why you do the additional manual step of merging by yourself, if a PR is approved, the bot will merge it for you ;)

The initial comment of the bot, that a PR needs approval and who is responsible for review/approve might be obvious, but especially to new contributors, it might be helpful.

Nevertheless, if you can not live with these helpers, feel free to work with @Gregory-Pereira to reconfigure Prow for this repo.

**Comment by Gkrumbach07** [comment]
any update on this @frenzymadness?

**Comment by frenzymadness** [comment]
@Gkrumbach07 I still think I don't need the bot here. But I'm not alone anymore so what do you @VannTen think?

**Comment by VannTen** [comment]
The lifecycle labels and auto-closing should be disabled now for all
repos under thoth-station/

Regarding the tide stuff (approved and lgtm labels and automerging) I'd
rather keep them, in particular the lgtm (can only be put by someone
else than a PR author if I'm correct) works pretty well to be sure to
have a least two set of eyes on stuff going into the main branch.

**Comment by Gkrumbach07** [comment]
@frenzymadness @VannTen Is there any other actions to be done regrading the Thoth bot on this repo? If not I will close this issue

**Comment by VannTen** [comment]
The current state should be :
- no lifecycle handling by prow.
- prow auto-merge PR when they have `approved` + `lgtm` labels.

If you're ok with that, we can close.

**Comment by frenzymadness** [comment]
Okay. I'm closing this now. Thanks to all of you.
