### ISSUE TITLE
Support for "legacy" source types via Poetry

### ISSUE THREAD

**Issue by avfarooq** [thoth-station/micropipenv#246]
Poetry designates the source type for every package as 'legacy' in the poetry.lock file if using a 3rd party or proxy repository as I am.

Now micropipenv only supports the source type to be 'git' or 'directory'

I kindly ask to support the 'legacy' value for source type as well, so that micropipenv can be used within an s2i container to build an image via poetry.lock and pyproject.toml files.

Thanks in advance for any help.

**Comment by frenzymadness** [comment]
Hi. Could you please provide us an example of pyproject.toml and poetry.lock we can use to reproduce the issue?

**Comment by avfarooq** [comment]
> Hi. Could you please provide us an example of pyproject.toml and poetry.lock we can use to reproduce the issue?

My bad on the delay. I'll try to respond today with an example.

**Comment by avfarooq** [comment]
I have attached an example demo repo which has the Poetry example files that replicate this issue. For some context, repositories that use the [Simple Repository API](https://peps.python.org/pep-0503/) are designated by Poetry as type`legacy` .. and this prevents the usage of Micropipenv. I'd like to be able to use micropipenv within an s2i builder image as it's one way to use Poetry without having to make a custom dockerfile.  Please let me know if you have any questions.

[flask-demo.tar.gz](https://github.com/thoth-station/micropipenv/files/9585968/flask-demo.tar.gz)

**Comment by frenzymadness** [comment]
Thanks for the demo. I'm already working on it and it helped me a lot to understand how poetry and pipenv handle package sources.

**Comment by frenzymadness** [comment]
Could you please help me verify that the fix I've prepared and the tests together with it make sense? See the linked PR. Thank you.

**Comment by frenzymadness** [comment]
@avfarooq do you plan to take a look at the changes anytime soon? If you don't, please say so and I'll merge it and release a new version today or tomorrow.

**Comment by frenzymadness** [comment]
> Sorry about the super late reply but yes I think the changes are great. Thank you so much! I really appreciate it.

A late reply is much better than a no reply. Thanks for that!
