### ISSUE TITLE
Support for "url" source type via Poetry

### ISSUE THREAD

**Issue by boddie2** [thoth-station/micropipenv#251]
If the source type of a package is 'url', micropipenv fails to install it -> 'micropipenv supports Git VCS or directories, got url instead'

Example of a package from a poetry.lock which fails to install:

[[package]]
name = "en-core-web-sm"
version = "3.0.0"
description = "English pipeline optimized for CPU. Components: tok2vec, tagger, parser, senter, ner, attribute_ruler, lemmatizer."
category = "main"
optional = false
python-versions = "*"

[package.dependencies]
spacy = ">=3.0.0,<3.1.0"

[package.source]
type = "url"
url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz"

**Comment by VannTen** [comment]
/kind feature
/triage accepted
Looks like worthy addition.

**Comment by frenzymadness** [comment]
@VannTen do you plan to take a look at this?

**Comment by VannTen** [comment]
Not before next January I'm afraid.

**Comment by frenzymadness** [comment]
The fix is simpler than I thought. Could you please take a look at the PR and help me with testing?
