### ISSUE TITLE
micropipenv can't parse Poetry lock file format 2.0

### ISSUE THREAD

**Issue by AntiCompositeNumber** [thoth-station/micropipenv#252]
**Describe the bug**
micropipenv can't parse Poetry lock file format 2.0, which includes a `files` attribute. 

**To Reproduce**
1. Install current Poetry (1.3)
2. Run `poetry update` or `poetry lock` to regenerate the lockfile
3. Attempt to run micropipenv install
4. `Failed to parse poetry.lock and pyproject.toml: 'files'`

**Expected behavior**
The `files` attribute should be parsed correctly or ignored.

**Additional context**
See python-poetry/poetry#6393

**Comment by frenzymadness** [comment]
Thanks for the report! I'll take a look. I'm not a user of poetry myself so it might take a while but from the linked PR it seems that only the structure has been changed but the content should be similar.

**Comment by AntiCompositeNumber** [comment]
The file data wasn't removed, it was just moved.

```diff
diff --git a/poetry.lock.old b/poetry.lock
index 1109733..8f1d7bf 100644
--- a/poetry.lock.old
+++ b/poetry.lock
@@ -1,3 +1,5 @@
+# This file is automatically @generated by Poetry and should not be changed by hand.
+
 [[package]]
 name = "urllib3"
 version = "1.26.13"
@@ -5,6 +7,10 @@ description = "HTTP library with thread-safe connection pooling, file post, and
 category = "main"
 optional = false
 python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*"
+files = [
+    {file = "urllib3-1.26.13-py2.py3-none-any.whl", hash = "sha256:47cc05d99aaa09c9e72ed5809b60e7ba354e64b59c9c173ac3018642d8bb41fc"},
+    {file = "urllib3-1.26.13.tar.gz", hash = "sha256:c083dd0dce68dbfbe1129d5271cb90f9447dea7d52097c6e0126120c521ddea8"},
+]
 
 [package.extras]
 brotli = ["brotli (>=1.0.9)", "brotlicffi (>=0.8.0)", "brotlipy (>=0.6.0)"]
@@ -12,12 +18,6 @@ secure = ["certifi", "cryptography (>=1.3.4)", "idna (>=2.0.0)", "ipaddress", "p
 socks = ["PySocks (>=1.5.6,!=1.5.7,<2.0)"]
 
 [metadata]
-lock-version = "1.1"
+lock-version = "2.0"
 python-versions = "^3.10"
 content-hash = "243d3fb67bbe1965e1d81eb651062f8136c8ee4a26bab9e630f38f19c278b3a3"
-
-[metadata.files]
-urllib3 = [
-    {file = "urllib3-1.26.13-py2.py3-none-any.whl", hash = "sha256:47cc05d99aaa09c9e72ed5809b60e7ba354e64b59c9c173ac3018642d8bb41fc"},
-    {file = "urllib3-1.26.13.tar.gz", hash = "sha256:c083dd0dce68dbfbe1129d5271cb90f9447dea7d52097c6e0126120c521ddea8"},
-]
```
[Here](https://gist.github.com/AntiCompositeNumber/6670f2bcb52963f0fe92bb3296210d06) is a gist with a sample old and new lock file.

**Comment by frenzymadness** [comment]
Thank you! You are right, I was using the wrong poetry version. I'm working on a fix so PR should be ready for review soon.

**Comment by frenzymadness** [comment]
PR #253 is now ready for review.

**Comment by frenzymadness** [comment]
Thanks for your help and the report. The problem is fixed and the fix is released.
