### ISSUE TITLE
[Poetry] Micropipenv mixing production and dependency lists during install

### ISSUE THREAD

**Issue by eganma-umich** [thoth-station/micropipenv#288]
**Describe the bug**
Using micropipenv to install dependencies from poetry in the python s2i builder image provided by Red Hat ([ENABLE_MICROPIPENV](https://github.com/sclorg/s2i-python-container/tree/master/3.9#environment-variables)) incorrectly groups some production/default dependencies with the development dependencies during installation.

Containers made from the resulting image are not be able to start due to missing packages.

**To Reproduce**
Have not tried reproducing locally.

Attached are minimal pyproject.toml and poetry.lock files that exhibit the problem when deployed with the builder image. File extensions were changed to txt since GitHub blocked attaching the files with their correct extensions.

Also attached is the builder image container log showing that a production dependency is being grouped with the development dependencies by micropipenv during installation.

**Expected behavior**
Production/default dependencies to not be grouped with development dependencies during installation.

**Additional context**
Poetry version: 1.6.1
Micropipenv version: 1.5.1

Maybe related to issue #284?

[pyproject.toml.txt](https://github.com/thoth-station/micropipenv/files/13190142/pyproject.toml.txt)
[poetry.lock.txt](https://github.com/thoth-station/micropipenv/files/13190140/poetry.lock.txt)
[micropipenv-test-git-3-undefined.log](https://github.com/thoth-station/micropipenv/files/13190219/micropipenv-test-git-3-undefined.log)

**Comment by goern** [comment]
Hey @eganma-umich this sounds like a bug, we would be really happy about contributions, so if you have some time to share ... ;)

@frenzymadness Is that something you can have a look at? do you have some time for it?

/king bug

**Comment by frenzymadness** [comment]
I'm on it now. The fix should be simple.
