### ISSUE TITLE
Github vs PyPI

### ISSUE THREAD

**Issue by frenzymadness** [thoth-station/micropipenv#36]
Hi.

The information on Github and PyPI is slightly out of sync:
* The latest release on PyPI is 0.1.1 but on Github, it's 0.1.0
* The tarball on PyPI does not contain tests folder (not a problem) and LICENSE (should be there)

I've tried to use both as a source for RPM package but neither is perfect so one of them has to be fixed before I continue.

**Comment by fridex** [comment]
> The information on Github and PyPI is slightly out of sync:
> 
> * The latest release on PyPI is 0.1.1 but on Github, it's 0.1.0

Sorry, I forgot to push. It should be OK now.

> * The tarball on PyPI does not contain tests folder (not a problem) and LICENSE (should be there)
> 

The sdist  on PyPI (v0.1.3) now comes with the LICENSE file (taken from the repo).

> I've tried to use both as a source for RPM package but neither is perfect so one of them has to be fixed before I continue.

Is there anything more missing I could help with?

**Comment by frenzymadness** [comment]
Well, the latest release on Github is 0.1.2 but PyPI contains 0.1.4. I'll use Github because I want to run tests during the rpm build.

**Comment by fridex** [comment]
> Well, the latest release on Github is 0.1.2 but PyPI contains 0.1.4. I'll use Github because I want to run tests during the rpm build.

agh, forgot to push tags... now it should be fine
