### ISSUE TITLE
Testing against all supported Pythons

### ISSUE THREAD

**Issue by frenzymadness** [thoth-station/micropipenv#43]
Hello.

From my point of view, it'd be very nice to have all supported Pythons in CI. In Python world, tools like tox are defacto standard to create a matrix of all supported Python with all supported dependencies. It'll make it also possible to test micropipenv against development version of Python and discover incompatibilities soon.

I know that the CI is already configured here but I don't understand its configuration and therefore I'd like to hear your opinions before I dive into implementation.

What do you think about it?

**Comment by fridex** [comment]
+1 on my side :+1: 

Another approach I could see is testing directly in the container image produced with `pip`+`micropipenv` present inside it (the pip version that is used in the container) - it might be more seen as "integration test" for s2i. The tox environment might be sufficient here though.

**Comment by fridex** [comment]
Another alternative is nox https://nox.thea.codes/en/stable/
