### ISSUE TITLE
Local installed packages

### ISSUE THREAD

**Issue by frenzymadness** [thoth-station/micropipenv#44]
Hello.

Is there a plan to support locally installed packages? I mean a situation when I have something like this in Pipfile.lock:

```
"e1839a8": {
    "editable": true,
    "path": "."
},
```

Currently, it's not recognized and micropipenv tries to install package `e1839a8` from PyPI.

**Comment by fridex** [comment]
It would be nice to support it from a feature-set point of view. :+1: 

BTW is there a direct use for this in Python s2i?

**Comment by frenzymadness** [comment]
I've discovered this during the implementation of micropipenv into s2i-python-container because we use it in one of our testing applications? https://github.com/sclorg/s2i-python-container/pull/372

**Comment by fridex** [comment]
This should be already implemented in #48.
