### ISSUE TITLE
Incompatibilities with the latest pip

### ISSUE THREAD

**Issue by frenzymadness** [thoth-station/micropipenv#55]
**Describe the bug**
It seems that `pip._internal.req` has been changed heavily and therefore `_requirements2pipfile_lock` has to be adjusted.

I've tried to fix it but I don't understand all the attributes it needs from requirements.

**To Reproduce**
1. Run tests with the latest pip (20.1.1)

It's probably not the best idea to depend on pip internal modules (I have some experience from other packages). Is bundling the functionality micropipenv needs an option? I am against bundling but it might be a candidate for an exception here if micropipenv does not need the whole pip.

**Comment by fridex** [comment]
Thanks for the report :+1: 

> It's probably not the best idea to depend on pip internal modules (I have some experience from other packages). Is bundling the functionality micropipenv needs an option? I am against bundling but it might be a candidate for an exception here if micropipenv does not need the whole pip.

I'm biased here. pip moved a lot of logic to internal state so pip devs/maintainers do not need to guarantee backward compatibility on a programming level. This can become a nightmare for micropipenv from maintenance point of view. There is not much functionality that micropipenv uses from pip and its bundled packaging, but it was not straightforward to bundle (or copy relevant parts).

I'll try to have a look at what needs to be changed and the cost of porting micropipenv to newer pip.

**Comment by fridex** [comment]
@frenzymadness #58 has been already merged and hence this issue was closed. Could you please verify this issue is no longer relevant on your side? Otherwise we could issue a new minor release.

**Comment by frenzymadness** [comment]
A minor release would be great so I'd be able to update the RPM. Should we create an issue to discuss how to test micropipenv with various versions of pip?
