### ISSUE TITLE
pytest-mypy and Python 3.8

### ISSUE THREAD

**Issue by frenzymadness** [thoth-station/micropipenv#63]
I'd like to discuss this change: #59 

The problem seems to be caused by the differences between Pipfile.lock when the file is generated by different versions of Python. When you do `pipenv lock` with Python 3.7, you get:

```
        "mypy": {
            "hashes": [
…
            ],
            "markers": "python_version >= '3.5' and python_version < '3.8'",
            "version": "==0.770"
```
which looks like mypy is not Python 3.8 compatible, but when you do the same with Python 3.8, you get the same version and different markers:

```
        "mypy": {
            "hashes": [
…
            ],
            "markers": "python_version >= '3.8'",
            "version": "==0.770"
```

This is caused by [this line](https://github.com/dbader/pytest-mypy/blob/master/setup.py#L41) in the pytest-mypy setup.py.

[Pipenv general recommendations](https://pipenv.pypa.io/en/latest/basics/#general-recommendations-version-control) says that if you target more than one Python version, which I believe micropipenv does, the Pipfile.lock file should not be included in VCS.

What do you think about it? Does this project need Pipfile at all? Given the fact that runtime dependencies are specified in setup.py and development dependencies in tox.ini.

**Comment by fridex** [comment]
Nice finding, thanks for spotting this. :+1: 

> [Pipenv general recommendations](https://pipenv.pypa.io/en/latest/basics/#general-recommendations-version-control) says that if you target more than one Python version, which I believe micropipenv does, the Pipfile.lock file should not be included in VCS.

This is something we should document in https://github.com/thoth-station/thamos/issues/413 (not micropipenv related, Thoth specific).

> What do you think about it? Does this project need Pipfile at all? Given the fact that runtime dependencies are specified in setup.py and development dependencies in tox.ini.

I'm fine with removing it, at least for now (IMO we should have locked dependencies even for tests to have reproducible test-suite). We added pipenv files as we do so for each Thoth repo, however micropipenv is a specific use case.

**Comment by fridex** [comment]
We can discuss pipenv files in a new issue that would cover testability of micropipenv following your comment in https://github.com/thoth-station/micropipenv/issues/55#issuecomment-633902684

**Comment by frenzymadness** [comment]
> We can discuss pipenv files in a new issue that would cover testability of micropipenv following your comment in [#55 (comment)](https://github.com/thoth-station/micropipenv/issues/55#issuecomment-633902684)

I am not sure that these two topics are related. I'd discuss pipenv files here if there is anything more to discuss, and I'll open a new issue for testing and pip.
