### ISSUE TITLE
File traversal and method selection

### ISSUE THREAD

**Issue by frenzymadness** [thoth-station/micropipenv#75]
Because my `/tmp` is full of garbage, I've probably found a bug during the final testing before the next release.

The "problem" is a way we detect which method of installation use which is based on:

https://github.com/thoth-station/micropipenv/blob/0bdce8b49c06881c17bc6510a5eb12bb02d4892c/micropipenv.py#L730-L749

This implementation means that if I have a project with `poetry.lock` in `/home/user/projects/application/` and `Pipfile.lock` in `/home/`, the detected method will be always `pipenv` because  the `Pipfile.lock` search is done first and it's found no matter how far it is.

In my humble opinion, `poetry.lock` in `/home/user/projects/application/` should take precedence.

This seems to be a problem only in the `install` function because all other usages (like in read_* functions) are looking for specific files based on the method detected in `install`.

Given the fact that the path to the right file might be as long as CWD or shorter, I'd try to get paths to all possible files and use the one with the longest path. What do you think about it? I can prepare a PR if you agree with the described solution.

**Comment by fridex** [comment]
Thanks for spotting this. I tried to [document this behavior in the README file](https://github.com/thoth-station/micropipenv/blob/02d8a86/README.rst#micropipenv-install). But it's misleading for this case.

> Given the fact that the path to the right file might be as long as CWD or shorter, I'd try to get paths to all possible files and use the one with the longest path. What do you think about it? I can prepare a PR if you agree with the described solution.

Yes, this might be a better approach when multiple lock files are found in the parent directories. Considering we keep the priority of lock files untouched when determining method I like this change. :+1:
