### ISSUE TITLE
Start maintaining CHANGELOG

### ISSUE THREAD

**Issue by fridex** [thoth-station/micropipenv#77]
**Is your feature request related to a problem? Please describe.**

As a user of micropipenv, I would like to see what notable changes were made to the new release so that I can see any new features and breaking changes.

**Describe the solution you'd like**

A CHANGELOG file maintained along the sources, possibly use GitHub releases for this.

**Describe alternatives you've considered**

Let's discuss them.

---

It would be nice to start maintaining a CHANGELOG so that users see what has changed across releases. @frenzymadness what would be the best way to integrate with you and Python s2i and rpm on your side?

We have an ongoing effort to automatically generate CHANGELOG entries so this might be helpful to see how to do it properly to be compliant also with Fedora world.

I've created a [GitHub release](https://github.com/thoth-station/micropipenv/releases/tag/v0.2.0), but it might not be sufficient enough. We have also a [CHANGELOG](https://github.com/thoth-station/micropipenv/blob/master/CHANGELOG.md) file available in the GitHub repository. What should go inside and should we follow any guidelines for the CHANGELOG so that it is easily machine-readable later on?

**Comment by frenzymadness** [comment]
A changelog is definitely useful if a user or package maintainer is not directly involved in development. For example, if I see a breaking change in a changelog I immediately know that I cannot update a package in released versions of Fedora and I do it only for rawhide and more carefully.
A changelog might be a part of RPM (as a regular file in doc folder) but it's neither parsed nor processed in any other automatic way. In other words, our changelog might be included in any way that will serve us well.
