### ISSUE TITLE
Confusing licensing

### ISSUE THREAD

**Issue by hroncok** [thoth-station/micropipenv#80]
**Describe the bug**
I don't understand the licencing of micrpipenv. Is it LGPL or GPL? 

- [classifier says](https://github.com/thoth-station/micropipenv/blob/00025232496c898c660400b494c5c85e1a019166/setup.py#L42) License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)
- [license says](https://github.com/thoth-station/micropipenv/blob/00025232496c898c660400b494c5c85e1a019166/setup.py#L35) GPLv3+
- [micropipenv.py says](https://github.com/thoth-station/micropipenv/blob/00025232496c898c660400b494c5c85e1a019166/micropipenv.py#L6) GNU Lesser General Public License ... version 3 of the License, or  any later version.
- [LICENSE](https://github.com/thoth-station/micropipenv/blob/master/LICENSE) is a symbolic link to [LICENSE-LGPL](https://github.com/thoth-station/micropipenv/blob/master/LICENSE-LGPL)
- there is [LICENSE-GPL](https://github.com/thoth-station/micropipenv/blob/master/LICENSE-GPL) file as well, why?

See also https://github.com/thoth-station/micropipenv/pull/71

**To Reproduce**
1. Try to figure out the license of micropipenv

**Expected behavior**
The license should be easily discoverbale trough the classifier, license tag, LICENSE file and the header comment.

**Screenshots**
![_](https://user-images.githubusercontent.com/2401856/83823055-2b1f4000-a6d3-11ea-91c6-5d9f35363fd4.png)

**Additional context**
No context.

**Comment by fridex** [comment]
Based on [this licensing manual](https://www.gnu.org/licenses/gpl-howto.en.html):

> You should also include a copy of the license itself somewhere in the distribution of your program. All programs, whether they are released under the GPL or LGPL, should include the text version of the GPL. In GNU programs we conventionally put the license in a file called COPYING.
> ..
> If you are releasing your program under the Lesser GPL, you should also include the text version of the LGPL, usually in a file called COPYING.LESSER. Please note that, since the LGPL is a set of additional permissions on top of the GPL, it's crucial to include both licenses so users have all the materials they need to understand their rights.

See discussion [after this comment](https://github.com/thoth-station/micropipenv/pull/71#issuecomment-636676543) where we discussed this.

Basically, we included both licence files based on suggestions on gnu.org how to. Sadly, GitHub does not follow symlinks for the LICENSE file so it does not detect the license correctly in the "View license" tab of the project (so we can delete `LICENSE`).

If you have any suggestions, feel free to bring them up.

**Comment by hroncok** [comment]
I see. Let's document this in README as well?

**Comment by fridex** [comment]
Good idea. :+1:  I opened #82 PTAL.

Also, GitHub documents how the detection is done in:

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#detecting-a-license

> If your repository is using a license that is listed on the Choose a License website and it's not displaying clearly at the top of the repository page, it may contain multiple licenses or other complexity. To have your license detected, simplify your LICENSE file and note the complexity somewhere else, such as your repository's README file.

It might be good idea to change content of ``LICENSE`` file so that GitHub correctly detects the license. It does not need to be shipped with the application (the same behavior as of now).
