### ISSUE TITLE
Enable package installation from file

### ISSUE THREAD

**Issue by harshad16** [thoth-station/micropipenv#99]
**Is your feature request related to a problem? Please describe.**
As some packages are not available as PyPI packages, it would be great to have a feature to install them from file directly.
Faced a similar issue while installing spacy packages. 

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
spacy = ">=2.3.0,<2.4.0"
en-core-web-sm = {file = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.0/en_core_web_sm-2.3.0.tar.gz"}
numpy = "*"

[requires]
python_version = "3.6" 
```

**Describe the solution you'd like**
A package can be installed from a file via pipenv , would like to have a feature to install via micropipenv.
I don't have clear solution for this.

**Describe alternatives you've considered**
None

**Additional context**
when tried to install the package in pipfile through micropipenv, this is the error response.
```
ERROR: Could not find a version that satisfies the requirement en-core-web-sm==2.3.0 (from -r /tmp/requirements.txtkjlus15h (line 2)) (from versions: none)
ERROR: No matching distribution found for en-core-web-sm==2.3.0 (from -r /tmp/requirements.txtkjlus15h (line 2))
Failed to install requirements, dependency 'en-core-web-sm' could not be installed
subprocess exited with status 3
subprocess exited with status 3
error building at STEP "RUN /opt/app-root/builder/assemble": exit status 3
```

**Comment by fridex** [comment]
As a temporary workaround until #100 gets merged and released, you can substitute the requirement with:

```
git+https://github.com/explosion/spacy-models@en_core_web_sm-2.3.0#egg=spacy-models
```
